# Generated by Django 4.2.3 on 2023-07-26 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_matricula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='nivel',
            new_name='periodo',
        ),
    ]
